<?php
/**
 * 紧急修复脚本 - 删除错误的 index.php
 * 访问此文件即可自动修复
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');

$results = [
    'time' => date('Y-m-d H:i:s'),
    'actions' => []
];

// 获取当前目录
$currentDir = __DIR__;

// 检查 index.php 是否存在（排除自身）
$indexPhpPath = $currentDir . '/index.php';
$thisFile = __FILE__;

// 如果 index.php 存在且不是当前文件
if (file_exists($indexPhpPath) && realpath($indexPhpPath) !== realpath($thisFile)) {
    // 尝试删除
    if (@unlink($indexPhpPath)) {
        $results['actions'][] = 'Deleted: ' . $indexPhpPath;
    } else {
        $results['actions'][] = 'Failed to delete: ' . $indexPhpPath . ' (permission denied)';
    }
} else {
    $results['actions'][] = 'index.php does not exist or is this file';
}

// 检查 index.html
$indexHtmlPath = $currentDir . '/index.html';
if (file_exists($indexHtmlPath)) {
    $results['actions'][] = 'index.html exists - OK';
} else {
    $results['actions'][] = 'WARNING: index.html not found!';
}

// 创建 .htaccess 确保 index.html 优先
$htaccessPath = $currentDir . '/.htaccess';
$htaccessContent = "# Auto-generated by fix script\nDirectoryIndex index.html index.php\n";

if (file_exists($htaccessPath)) {
    $results['actions'][] = '.htaccess already exists';
} else {
    if (@file_put_contents($htaccessPath, $htaccessContent)) {
        $results['actions'][] = 'Created .htaccess with index.html priority';
    } else {
        $results['actions'][] = 'Failed to create .htaccess';
    }
}

// 最终验证
$results['final_check'] = [
    'index_php_exists' => file_exists($indexPhpPath),
    'index_html_exists' => file_exists($indexHtmlPath),
    'htaccess_exists' => file_exists($htaccessPath)
];

echo json_encode($results, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
